### ISSUE TITLE
shoulda matchers deprecation warning

### ISSUE THREAD

**Issue by ghembo** [tinfoil/shoulda-kept-assign-to#5]
when running a spec using assign_to matcher I get the following warning:

```
Deprecation Warnings:

--------------------------------------------------------------------------------
Shoulda::Matchers::ActionController::AssignToMatcher implements a legacy RSpec matcher
protocol. For the current protocol you should expose the failure messages
via the `failure_message` and `failure_message_when_negated` methods.
```

**Comment by jaredmoody** [comment]
This is already done on master, there just needs to be a new gem release. For now you can update your Gemfile to: 

`gem 'shoulda-kept-assign-to', github: 'tinfoil/shoulda-kept-assign-to'`

**Comment by raszi** [comment]
When are you going to release this?

**Comment by bsedat** [comment]
Sorry for the long wait! I've pushed v1.1.0 to rubygems.
