### ISSUE TITLE
README change: does not contain all of shoulda

### ISSUE THREAD

**Issue by jeremywadsack** [tinfoil/shoulda-kept-assign-to#6]
In the README it says:

> This gem includes all of the current version of shoulda-matchers, and it adds the 'assign_to' matcher back in, just the way it was before it was mercilessly destroyed.

However, this gem only contains the single matcher for `assign_to` (which is how it should be).

Also, the `Gemfile` example should be updated to include the `should-matchers` gem:

```ruby
group :development, :test do
  gem "shoulda-matchers"
  gem "shoulda-kept-assign-to"
end
```

**Comment by bsedat** [comment]
I think we already define a dependency on the main shoulda-matchers gem (https://rubygems.org/gems/shoulda-kept-assign-to) so the other matchers are pulled in via that.

**Comment by bsedat** [comment]
All taken care of now I think :smile:
